apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: samba
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "password-key" "providedValues" (list "password-value") "context" $) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: named-key-secret
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: named-key-secret
    template:
      type: Opaque
      data:
        named-keys.conf: |
          key "externaldns" {
                  algorithm hmac-sha256;
                  secret "{{ `{{ .key | toString }}` }}";
          };
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: secrets/data/samba/tsig
        property: key