name: Publish image
on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/stopdenbus/samba/samba
          flavor: |
            latest=true
          tags: |
            type=raw,value={{date 'YY.MM.DD'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Cleanup
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
          keep-n-tagged: 2
          packages: samba/samba
          older-than: 4 weeks
